const driverLicenceRegion = [
  { name: '서울[11]', value: '11', disabled: false },
  { name: '부산[12]', value: '12', disabled: false },
  { name: '경기[13]', value: '13', disabled: false },
  { name: '강원[14]', value: '14', disabled: false },
  { name: '충북[15]', value: '15', disabled: false },
  { name: '충남[16]', value: '16', disabled: false },
  { name: '전북[17]', value: '17', disabled: false },
  { name: '전남[18]', value: '18', disabled: false },
  { name: '경북[19]', value: '19', disabled: false },
  { name: '경남[20]', value: '20', disabled: false },
  { name: '제주[21]', value: '21', disabled: false },
  { name: '대구[22]', value: '22', disabled: false },
  { name: '인천[23]', value: '23', disabled: false },
  { name: '광주[24]', value: '24', disabled: false },
  { name: '대전[25]', value: '25', disabled: false },
  { name: '울산[26]', value: '26', disabled: false },
  { name: '경기북부[28]', value: '28', disabled: false },
];
const bankList = [
  { name: '산업은행', value: '02', disabled: false },
  { name: '기업은행', value: '03', disabled: false },
  { name: '국민은행', value: '04', disabled: false },
  { name: '수협중앙회', value: '11', disabled: false },
  { name: '지역농축협(단위 농협)', value: '12', disabled: false },
  { name: '우리은행', value: '20', disabled: false },
  { name: 'SC은행', value: '23', disabled: false },
  { name: '한국씨티은행', value: '27', disabled: false },
  { name: '대구은행', value: '31', disabled: false },
  { name: '부산은행', value: '32', disabled: false },
  { name: '광주은행', value: '34', disabled: false },
  { name: '제주은행', value: '33', disabled: false },
  { name: '전북은행', value: '37', disabled: false },
  { name: '새마을금고중앙회', value: '45', disabled: false },
  { name: '신협중앙회', value: '48', disabled: false },
  { name: '상호저축은행', value: '50', disabled: false },
  { name: 'HSBC은행', value: '54', disabled: false },
  { name: '우체국', value: '71', disabled: false },
  { name: 'KEB하나은행', value: '81', disabled: false },
  { name: '신한은행', value: '88', disabled: false },
  { name: '케이뱅크', value: '89', disabled: false },
  { name: '카카오뱅크', value: '90', disabled: false },
];
const cardList = [
  { title: 'BC카드', disabled: false },
  { title: '국민카드', disabled: false },
  { title: '농협카드', disabled: false },
  { title: '롯데카드', disabled: true },
  { title: '삼성카드', disabled: true },
  { title: '신한카드', disabled: true },
  { title: '하나카드', disabled: true },
  { title: '현대카드', disabled: true },
  { title: '카카오카드', disabled: true },
  { title: '우체국카드', disabled: true },
  { title: 'K뱅크', disabled: true },
  { title: '아멕스카드', disabled: true },
  { title: '씨티카드', disabled: true },
  { title: '기타카드', disabled: true },
  { title: '우리카드', disabled: true },
];
const alttleTelecomList = [
  { title: '[SK망]SK 7모바일(SK텔링크)', disabled: false },
  { title: '[SK망]LG헬로모바일', disabled: true },
  { title: '[SK망]스마텔', disabled: true },
  { title: '[SK망]이야기 알뜰폰', disabled: true },
  { title: '[SK망]프리텔레콤', disabled: true },
  { title: '[SK망]에스원안심모바일', disabled: true },
  { title: '[SK망]유니컴즈', disabled: true },
  { title: '[SK망]아이즈모바일', disabled: true },
  { title: '[SK망]T플러스', disabled: true },
  { title: '[SK망]마이월드(SKT망)', disabled: true },
  { title: '[SK망]이마트(SKT망)', disabled: true },
  { title: '[SK망]조이텔(SKT망)', disabled: true },
  { title: '[KT망]KT M모바일', disabled: true },
  { title: '[KT망]에넥스텔레콤', disabled: true },
  { title: '[KT망]LG헬로모바일', disabled: true },
  { title: '[KT망]스마텔', disabled: true },
  { title: '[KT망]프리텔레콤', disabled: true },
  { title: '[KT망]세종텔레콤', disabled: true },
  { title: '[KT망]유니컴즈', disabled: true },
  { title: '[KT망]에스원안심모바일', disabled: true },
  { title: '[KT망]드림모바일', disabled: true },
  { title: '[KT망]위너스텔', disabled: true },
  { title: '[KT망]앤텔레콤', disabled: true },
  { title: '[KT망]CNcom', disabled: true },
  { title: '[KT망]코드모바일', disabled: true },
  { title: '[KT망]KT파워텔', disabled: true },
  { title: '[KT망]에스로밍', disabled: true },
  { title: '[KT망]홈플러스(KT망)', disabled: true },
  { title: '[KT망]에이씨엔코리아(KT망)', disabled: true },
  { title: '[KT망]착한통신', disabled: true },
  { title: '[KT망]케이티스', disabled: true },
  { title: '[KT망]장성모바일한국', disabled: true },
  { title: '[KT망]아이즈비전(KT망)', disabled: true },
  { title: '[KT망]머천드코리아(KT망)', disabled: true },
  { title: '[KT망]제이씨티', disabled: true },
  { title: '[KT망]미니케이트', disabled: true },
  { title: '[KT망]아이원', disabled: true },
  { title: '[KT망]핀플레이(KT망)', disabled: true },
  { title: '[KT망]파인디지털', disabled: true },
  { title: '[KT망]KCT(KT망)', disabled: true },
  { title: '[KT망]이비카드(KT망)', disabled: true },
  { title: '[KT망]와이엘랜드', disabled: true },
  { title: '[KT망]큰사람KT', disabled: true },
  { title: '[KT망]니즈텔레콤(KT망)', disabled: true },
  { title: '[KT망]케이티스카이라이프(KT망)', disabled: true },
  { title: '[KT망]에이프러스', disabled: true },
  { title: '[KT망]케이티엠모바일', disabled: true },
  { title: '[U+망]유플러스 알뜰 모바일', disabled: true },
  { title: '[U+망]스마텔', disabled: true },
  { title: '[U+망]이야기알뜰폰', disabled: true },
  { title: '[U+망]에넥스텔레콤', disabled: true },
  { title: '[U+망]프리텔레콤(인스코비)', disabled: true },
  { title: '[U+망]LG헬로모바일', disabled: true },
  { title: '[U+망]유니컴즈', disabled: true },
  { title: '[U+망]리브모바일', disabled: true },
  { title: '[U+망]아이즈모바일', disabled: true },
  { title: '[U+망]머천드코리아', disabled: true },
  { title: '[U+망]에스원안심모바일', disabled: true },
  { title: '[U+망]MTT', disabled: true },
  { title: '[U+망]대성홀딩스', disabled: true },
  { title: '[U+망]알뜰폰', disabled: true },
  { title: '[U+망]에이씨엔코리아(U+망)', disabled: true },
  { title: '[U+망]레그원', disabled: true },
  { title: '[U+망]도시락모바일(U+망)', disabled: true },
  { title: '[U+망]세종텔레콤(U+망)', disabled: true },
  { title: '[U+망]홈플러스(U+망)', disabled: true },
  { title: '[U+망]이마트(U+망)', disabled: true },
  { title: '[U+망]서경방송', disabled: true },
  { title: '[U+망]울산방송', disabled: true },
  { title: '[U+망]푸른방송', disabled: true },
  { title: '[U+망]남인천방송', disabled: true },
  { title: '[U+망]금강방송', disabled: true },
  { title: '[U+망]제주방송', disabled: true },
  { title: '[U+망]여유텔레콤(U+망)', disabled: true },
  { title: '[U+망]이지모바일(U+망)', disabled: true },
  { title: '[U+망]케이디디아이코리아(U+망)', disabled: true },
  { title: '[U+망]휴엘컴퍼니(U+망)', disabled: true },
  { title: '[U+망]조이텔(U+망)', disabled: true },
  { title: '[U+망]핀플레이(U+망)', disabled: true },
  { title: '[U+망]원텔레콤(U+망)', disabled: true },
  { title: '[U+망]핀샷(U+망)', disabled: true },
  { title: '[U+망]화인통신(U+망)', disabled: true },
  { title: '[U+망]KPMOLG', disabled: true },
  { title: '[U+망]엔티온텔레콤(U+망)', disabled: true },
  { title: '[U+망]인스코리아(U+망)', disabled: true },
  { title: '한국케이블텔레콤', disabled: true },
  { title: '온세텔레콤', disabled: true },
  { title: '기타 통신사', disabled: true },
];
const machineModelList = [
  { label: '갤럭시 Z Flip 4', value: '갤럭시 Z Flip 4', rating: 'safe' },
  { label: '갤럭시 Z Fold 4', value: '갤럭시 Z Fold 4', rating: 'safe' },
  { label: 'iPhone14 Pro Max', value: 'iPhone14 Pro Max', rating: 'safe' },
  { label: 'iPhone14 Pro', value: 'iPhone14 Pro', rating: 'safe' },
  { label: 'iPhone14 Plus', value: 'iPhone14 Plus', rating: 'safe' },
  { label: 'iPhone14', value: 'iPhone14', rating: 'safe' },
  { label: 'iPhone13 Pro Max', value: 'iPhone13 Pro Max', rating: 'safe' },
  { label: 'iPhone13 Pro', value: 'iPhone13 Pro', rating: 'safe' },
  { label: 'iPhone13', value: 'iPhone13', rating: 'safe' },
  { label: 'iPhone13 mini', value: 'iPhone13 mini', rating: 'safe' },
  { label: 'iPhone12 Pro Max', value: 'iPhone12 Pro Max', rating: 'safe' },
  { label: 'iPhone12 Pro', value: 'iPhone12 Pro', rating: 'safe' },
  { label: 'iPhone12', value: 'iPhone12', rating: 'safe' },
  { label: 'iPhone12 mini', value: 'iPhone12 mini', rating: 'safe' },
  { label: 'iPhone SE 3세대', value: 'iPhone SE 3세대', rating: 'safe' },
  { label: 'iPhone11 Pro', value: 'iPhone11 Pro', rating: 'safe' },
  { label: 'iPhone11', value: 'iPhone11', rating: 'safe' },
  { label: 'iPhone11 mini', value: 'iPhone11 mini', rating: 'safe' },
  { label: 'iPhone XR', value: 'iPhone XR', rating: 'safe' },
  { label: 'iPhone XS MAX', value: 'iPhone XS MAX', rating: 'safe' },
  { label: 'iPhone XS', value: 'iPhone XS', rating: 'safe' },
  { label: '그 외', value: '그 외', rating: 'safe' },
];
export {
  alttleTelecomList,
  bankList,
  cardList,
  driverLicenceRegion,
  machineModelList,
};
